#!/usr/bin/ruby

require 'spinning_cursor'

puts "\nYoutube Audio Downloader"

puts "Enter a video URL and press enter:"
urls = [gets.chomp]

more_urls_prompt =  "\nIf there are no more URLs, press enter; otherwise, enter another URL and press enter:"
puts more_urls_prompt
until (next_url = gets.chomp).empty?
   urls << next_url
   puts more_urls_prompt
end

urls = urls.map do |url|
	if url.match(/^www/)
		"https://" + url
	else
		url
	end
end

puts "\n Where should the mp3 files be saved? To use the default (~/Downloads), press enter without typing anything. To use the current directory, press . (period). To use any other directory, enter an absolute path."
destination_cmd = gets.chomp
destination_path = case destination_cmd
when ""
   "~/Downloads"
when "."
   `pwd`.chomp
else
   destination_cmd
end

puts "OK, downloading #{urls.length} track(s) to #{destination_path}."
urls.each_with_index do |url, index|
  SpinningCursor.run do
	banner "downloading"
	type :spinner
	delay 0.10
	action do
	  `cd #{destination_path} && youtube-dl --extract-audio --prefer-ffmpeg --audio-format mp3 --audio-quality 3 #{url} >/dev/null`
	end
	message "#{index + 1} downloaded"
  end
end

puts "done"   

