#!/usr/bin/ruby

puts "\nYoutube Audio Downloader (https://github.com/MaxPleaner/youtube-audio-downloader)"

puts "Enter a video URL and press enter:"
urls = [gets.chomp]

more_urls_prompt =  "\nIf there are no more URLs, press enter; otherwise, enter another URL and press enter:"
puts more_urls_prompt
until (next_url = gets.chomp).empty?
   urls << next_url
   puts more_urls_prompt
end

puts "\n Where should the mp3 files be saved? To use the default (~/Downloads), press enter without typing anything. To use the current directory, press . (period). To use any other directory, enter an absolute path."
destination_cmd = gets.chomp
destination_path = case destination_cmd
when ""
   "~/Downloads"
when "."
   `pwd`.chomp
else
   destination_cmd
end

puts "OK, downloading #{urls.length} track(s) to #{destination_path}."
urls.each_with_index do |url, index|
  `cd #{destination_path} && youtube-dl --extract-audio --audio-format mp3 --audio-quality 3 #{url} >/dev/null`
   puts "#{index + 1} downloaded"
end

puts "done"   

